### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by BertvanderVeen** [LCBC-UiO/galamm#181]
Hello! Cool package you have here.

I just wanted to say hi and let you know that I enjoyed reading the accompanying publication. "We" have a frequentist R-package that fits latent variable models to a range of response types as well ([gllvm](https://github.com/JenniNiku/gllvm)), but using variational approximations, and with the Laplace approximation via template model builder, and for community ecology.

Would be great to have a chat at some point, exchange ideas and all that!

All the best,
Bert

**Comment by osorensen** [comment]
Hello @BertvanderVeen, sorry about my late response. Somehow I've managed to turn off notifation to issues in this repository. 

Your gllvm package looks really nice, and I'd love to chat. It even looks like we're working in the same country??

**Comment by BertvanderVeen** [comment]
No worries, I would have sent an e-mail at some point. Yes, I work as a postdoc at the Mathematics department in Trondheim. We can schedule a zoom chat, unless you happen to visit Trondheim in the near future?
